const PaperItem = () => {
    return (
        <div>
            <div className="PaperItemBlcok">
                <h1>GIRAFFE: Representing Scenes as Compositional Generative Neural Feature Fields</h1>
                <span>link: https://arxiv.org/abs/2011.12100 tag: ???</span>
                <br></br>
                <span>generated by chatpdf</span><br></br>
                <span>
                當然可以！本文提出了一種使用組合式3D場景表示的創新方法，稱為GIRAFFE，用於可控圖像合成。作者提出了一種管道，可以生成逼真的圖像，同時允許對場景內容進行控制。

    GIRAFFE的關鍵創新在於使用組合生成神經��徵場來建模場景中的單個對象。這些特徵場可以被加法地組合起來創建複雜的場景，並且可以被操作以改變單個對象的形狀、外觀和位置。作者還使用神經渲染管道來高效地渲染場景。

    GIRAFFE的主要優點之一是其能夠解開場景中的單個對象，並允許對其屬性進行操作。這是在沒有明確監督的情況下實現的，使其比以前的方法更靈活和可擴展。

    作者通過幾個實驗和與基線方法的比較展示了GIRAFFE的有效性。他們表明，GIRAFFE可以生成具有可控內容的高質量圖像，並且可以泛化到訓練分佈之外的場景。

    總的來說，本文提出了一種創新的圖像合成方法，可以進一步推動計算機圖形學和計算機視覺領域的發展。通過使用組合式3D場景表示和神經渲染管道，GIRAFFE為可控圖像合成
                </span>
            </div>
            <div className="PaperItemBlock">
                <h1>港大發現如外賣平台預設不提供餐具 　每年可減少217億餐具消耗</h1>
                <span>http://www.aastocks.com/tc/stocks/news/infocast-news/IC4131373/1</span>
            </div>
        </div>
    )
}

export default PaperItem;